require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnchorLinkTopicsController do

  # This should return the minimal set of attributes required to create a valid
  # AnchorLinkTopic. As you add validations to AnchorLinkTopic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnchorLinkTopicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all anchor_link_topics as @anchor_link_topics" do
      anchor_link_topic = AnchorLinkTopic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:anchor_link_topics).should eq([anchor_link_topic])
    end
  end

  describe "GET show" do
    it "assigns the requested anchor_link_topic as @anchor_link_topic" do
      anchor_link_topic = AnchorLinkTopic.create! valid_attributes
      get :show, {:id => anchor_link_topic.to_param}, valid_session
      assigns(:anchor_link_topic).should eq(anchor_link_topic)
    end
  end

  describe "GET new" do
    it "assigns a new anchor_link_topic as @anchor_link_topic" do
      get :new, {}, valid_session
      assigns(:anchor_link_topic).should be_a_new(AnchorLinkTopic)
    end
  end

  describe "GET edit" do
    it "assigns the requested anchor_link_topic as @anchor_link_topic" do
      anchor_link_topic = AnchorLinkTopic.create! valid_attributes
      get :edit, {:id => anchor_link_topic.to_param}, valid_session
      assigns(:anchor_link_topic).should eq(anchor_link_topic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnchorLinkTopic" do
        expect {
          post :create, {:anchor_link_topic => valid_attributes}, valid_session
        }.to change(AnchorLinkTopic, :count).by(1)
      end

      it "assigns a newly created anchor_link_topic as @anchor_link_topic" do
        post :create, {:anchor_link_topic => valid_attributes}, valid_session
        assigns(:anchor_link_topic).should be_a(AnchorLinkTopic)
        assigns(:anchor_link_topic).should be_persisted
      end

      it "redirects to the created anchor_link_topic" do
        post :create, {:anchor_link_topic => valid_attributes}, valid_session
        response.should redirect_to(AnchorLinkTopic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved anchor_link_topic as @anchor_link_topic" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnchorLinkTopic.any_instance.stub(:save).and_return(false)
        post :create, {:anchor_link_topic => { "name" => "invalid value" }}, valid_session
        assigns(:anchor_link_topic).should be_a_new(AnchorLinkTopic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnchorLinkTopic.any_instance.stub(:save).and_return(false)
        post :create, {:anchor_link_topic => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested anchor_link_topic" do
        anchor_link_topic = AnchorLinkTopic.create! valid_attributes
        # Assuming there are no other anchor_link_topics in the database, this
        # specifies that the AnchorLinkTopic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnchorLinkTopic.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => anchor_link_topic.to_param, :anchor_link_topic => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested anchor_link_topic as @anchor_link_topic" do
        anchor_link_topic = AnchorLinkTopic.create! valid_attributes
        put :update, {:id => anchor_link_topic.to_param, :anchor_link_topic => valid_attributes}, valid_session
        assigns(:anchor_link_topic).should eq(anchor_link_topic)
      end

      it "redirects to the anchor_link_topic" do
        anchor_link_topic = AnchorLinkTopic.create! valid_attributes
        put :update, {:id => anchor_link_topic.to_param, :anchor_link_topic => valid_attributes}, valid_session
        response.should redirect_to(anchor_link_topic)
      end
    end

    describe "with invalid params" do
      it "assigns the anchor_link_topic as @anchor_link_topic" do
        anchor_link_topic = AnchorLinkTopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnchorLinkTopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => anchor_link_topic.to_param, :anchor_link_topic => { "name" => "invalid value" }}, valid_session
        assigns(:anchor_link_topic).should eq(anchor_link_topic)
      end

      it "re-renders the 'edit' template" do
        anchor_link_topic = AnchorLinkTopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnchorLinkTopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => anchor_link_topic.to_param, :anchor_link_topic => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested anchor_link_topic" do
      anchor_link_topic = AnchorLinkTopic.create! valid_attributes
      expect {
        delete :destroy, {:id => anchor_link_topic.to_param}, valid_session
      }.to change(AnchorLinkTopic, :count).by(-1)
    end

    it "redirects to the anchor_link_topics list" do
      anchor_link_topic = AnchorLinkTopic.create! valid_attributes
      delete :destroy, {:id => anchor_link_topic.to_param}, valid_session
      response.should redirect_to(anchor_link_topics_url)
    end
  end

end
